### ISSUE TITLE
When the App is swiped out from the pager, upload freezes up

### ISSUE THREAD

**Issue by K-7** [gotev/android-upload-service#100]
Using the latest 'net.gotev:uploadservice:2.0.1' package when the App gets closed the upload which is happening in the background gets stopped. Only when the App is got back to foreground the upload happens.

**Comment by gotev** [comment]
I've experienced the same behaviour like you described in the following condition on Android 4.4+:
- an upload is running in the background without a notification
- the user swipes out the app from the pager

This happens because when the user swipes out the app from the pager, the root intent used to launch the app gets removed, and so the app's main execution thread is stopped. When you are running an upload without a notification, or you have set [UploadService.EXECUTE_IN_FOREGROUND = false](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/UploadService.java#L50), the service's main thread runs in the same thread as your app, and so it gets stopped. A solution for this case with the current release is to set a notification configuration for the upload. The progress will be displayed in the notification center and the service will run in the foreground (By default `UploadService.EXECUTE_IN_FOREGROUND = true`). When you swipe out the app, the upload should continue.

I've done some research about how to prevent that the service gets stopped when the user swipes out the app while it runs in the background. A possible solution could be [this](http://www.vogella.com/tutorials/AndroidServices/article.html#service_process), but testing is needed.

Just to get more insights of your use case...when you get back into your app, the upload resumes from where is was, gets restarted from the beginning, or nothing happens until you explicitly trigger a new upload?

**Comment by K-7** [comment]
The behaviour I observed is as follow -
1. I trigger the upload service, the upload starts and upload notification proceeds
2. I swipe out the App, the upload notification freezes. The service is mostly killed or pasued (not sure)
3. I reopen the app and trigger the upload service, the upload happens smoothly
4. As I had written a CONNECTIVITY_SERVICE for my App I could figure out that when the upload service gets freezon on swipping out the App, and I try to turn off and on my WiFi, using CONNECTIVITY_SERVICE I could triggered the upload service and upload worked fine though the App was closed
5. Only issue Iam facing now is the moment the App is swipped out the Upload service gets frozen

I tried it out in Android 5.1 and Android 6.0 both the cases I am facing the same isssue

**Comment by gotev** [comment]
Yeah, it's exactly the same behaviour. I also have experienced that on Android 4.4, 5.1 and 6.0 but to date I haven't found a way to prevent that. It's standard Android behaviour. When you swipe out the app, the process gets killed by the system. Since the service is bound to the app's process, it gets killed, too, so the current upload freezes. If you don't swipe out the app from the pager, but you leave it there while using some other app, it will work fine. Apps like Telegram or WhatsApp have background services with a persistent job queue and support for resume, so when you swipe them out and the services gets restarted, they continue their work from where it was left. Unfortunately, standard HTTP/Multipart upload does not support resume, so even if you implement a persistent job queue, the last upload will be restarted. I'm open to ideas if you have some.

There are some tricks around, like adding a periodic task with AlarmManager or relaunching the service from another one, but they sound more like a hack and so I don't consider them as options.

**Comment by K-7** [comment]
Thank you, let me figure out what best I can do.

**Comment by gotev** [comment]
Currently the service has [START_STICKY](http://developer.android.com/reference/android/app/Service.html#START_STICKY) policy. Another option could be switching to [ START_REDELIVER_INTENT](http://developer.android.com/reference/android/app/Service.html#START_REDELIVER_INTENT) so the last intent sent to the service will be automatically redelivered upon restart. That, however, is a partial solution, as the last running upload will be restarted from the beginning. Let me know if you discover something new or if you find a way to not interrupt the background service when the app gets swiped out. I'll do some research and tests and I'll report my results here.

**Comment by gotev** [comment]
@K-7 Have you discovered something? I've made some tests, but when you swipe out the app, I've not found a way to prevent the service from being killed
