### ISSUE TITLE
send extra param to php

### ISSUE THREAD

**Issue by sajadpm** [gotev/android-upload-service#102]
hi , thanks for lib ... so great , cant good speak en , how send extra param to sever php ? 
`(isset($_POST['file_type-up'])) ? $_POST['file_type-up'] : '';
switch($type_file){`
thanks

**Comment by gotev** [comment]
Please read the [wiki](https://github.com/gotev/android-upload-service/wiki/Recipes) and check the docs before posting issues like this, because the answer was already [here](http://gotev.github.io/android-upload-service/javadoc/net/gotev/uploadservice/MultipartUploadRequest.html#addParameter-java.lang.String-java.lang.String-). I'm closing this one.
