### ISSUE TITLE
An unbind service error

### ISSUE THREAD

**Issue by dht** [gotev/android-upload-service#129]
I get this error when finishing an activity:
```java
 E/ActivityThread: Activity com.github.dht.screenger.activities.ScreengerActivity has leaked ServiceConnection azy@16fd5a05 that was originally bound here
                                                                        android.app.ServiceConnectionLeaked: Activity com.github.dht.screenger.activities.ScreengerActivity has leaked ServiceConnection azy@16fd5a05 that was originally bound here
```
I use this code to generate the uploadRequest:
```java
String uploadId = new BinaryUploadRequest(this, "https://api.parse.com/1/files/photo.png")
    .addHeader("X-Parse-Application-Id", "xxx")
    .addHeader("X-Parse-REST-API-Key", "xxxx")
    .addHeader("Content-Type", "image/jpg")
    .setFileToUpload(newFilepath)
    .addParameter("data", "{\"name\":\"Andrew\",\"picture\":{\"name\":\"profile.png\",\"__type\": \"File\"}}")
    .setNotificationConfig(config)
    .setMaxRetries(2)
    .startUpload();
```
Is there something I need to do on the onDestroy?
I do want the upload to go on regardless of the activity's end...

**Comment by gotev** [comment]
The code you used is ok. Android Upload Service runs in the background regardless of the activity life cycle, so when you create a request and start it, like you've done, you can safely exit from your activity and the upload will be continued in the background (unless you swipe out the app from the pager, in which case things gets more complicated #100 ). If you have used a broadcast receiver inside your activity, check if you have properly unregistered it. You can find a detailed explanation [here](http://gotev.github.io/android-upload-service/javadoc/net/gotev/uploadservice/UploadServiceBroadcastReceiver.html).

From what I see in your report, It doesn't seem to me that the service which is leaking is Android Upload Service:
```java
E/ActivityThread: Activity com.github.dht.screenger.activities.ScreengerActivity has leaked ServiceConnection azy@16fd5a0 that was originally bound here
```
because it does not support binding with activities, as it runs completely detached and I don't see it in the log. Check if you have some services bound to the activity, which are not unbinded in the `onDestroy`.
