### ISSUE TITLE
on oneDrive file upload give me 400 invalidRequest (Invalid Content-Range Header valus)

### ISSUE THREAD

**Issue by gaurnagchauhan** [gotev/android-upload-service#130]

**Comment by gotev** [comment]
Provide more details

**Comment by gaurnagchauhan** [comment]
just tell me how to see network traffic by setting log level

**Comment by gotev** [comment]
@gaurnagchauhan you have to use [Wireshark](https://github.com/gotev/android-upload-service/wiki/Testing%20and%20working%20examples) to see the complete body of the requests and responses from your server.

**Comment by gaurnagchauhan** [comment]
setting HttpLoggingInterceptor to okhttp client will not work?

**Comment by gotev** [comment]
[Unfortunately not](https://github.com/gotev/android-upload-service/issues/122#issuecomment-217398645) at the moment. Interceptors are not supported currently in the `OkHttp` implementation for Upload Service. That may be also the cause of your 400 bad request, if you set headers in the interceptors.

**Comment by gaurnagchauhan** [comment]
i try to upload files in onedrive with the help of BinaryUploadRequest. I remove header "Authorization" then also BinaryUploadRequest make call and gives me 400, {"error":{"code":"invalidRequest","message":"Invalid Content-Range header value"}}

**Comment by gaurnagchauhan** [comment]
I can upload files with me help of okHttp. https://dev.onedrive.com/items/upload_large_files.htm#upload-fragments

**Comment by gaurnagchauhan** [comment]
can i set my range header on BinaryUploadRequest? and if yes then how?

**Comment by gotev** [comment]
@gaurnagchauhan to have an out-of-the-box support for OneDrive, since [the docs](https://dev.onedrive.com/items/upload_large_files.htm) are really good, but to implement it client-side some effort is required, I think the best will be to create a plugin for UploadService, by implementing a new UploadRequest type specifically for OneDrive and a new UploadTask which will handle all the protocol part in the background. Basically, after that this has been implemented, as a library user you will simply have to add a dependency in your gradle build file and then be able to write something like this:
```java
new OneDriveUploadRequest(...)
 .setFileToUpload(....)
 .startUpload();
```
If you want to contribute, [this](https://github.com/gotev/android-upload-service/wiki/Developer's%20manual) will be helpful. I'm still writing it, so without any doubt there is some missing information, but with your feedback I could improve that too. I can help with the implementation, too.

**Comment by gaurnagchauhan** [comment]
dose i set my Content range on binaryUploadRequest?
