### ISSUE TITLE
Ability to upload Uri, not only String path

### ISSUE THREAD

**Issue by dominolog** [gotev/android-upload-service#134]
It would be nice to pass Uri to upload service instead of passing String path to file.

**Comment by gotev** [comment]
Wouldn't it be best and easier to be able to pass a `File` object instance instead of `Uri`? Supporting `Uri` means also adding code to properly handle it. Something like [this](https://github.com/iPaulPro/aFileChooser/blob/master/aFileChooser/src/com/ipaulpro/afilechooser/utils/FileUtils.java#L257). If you have some suggestions, you're welcome.

**Comment by stephentuso** [comment]
Files may not be the best for all cases. For example, media received from the gallery/camera is in the form of Android content Uris. It doesn't seem guaranteed that you can get a file path from a content Uri. It is, however, easy to get an `InputStream` with `context.getContentResolver().openInputStream(uri)`.

**Comment by dominolog** [comment]
+1 to @stephentuso comment. Local Uri can be opened as InputStream and the entire Android content model is based on Uri. In most cases the library is used for transferring local files obtained as Uris from ContentResolver.

**Comment by gotev** [comment]
I also agree. Feel free to fork the project and implement that, then send me a pull request.

**Comment by gotev** [comment]
Merge with #137
