### ISSUE TITLE
Add On Restart Request event/callback

### ISSUE THREAD

**Issue by LinkedHK** [gotev/android-upload-service#135]
Hi. Thank you for helpful library.

I believe there is no way to catch / prevent the restart based on server response. I'm making upload to the server which has full disk. once upload progress  reaches 100% the library retries(specific number of times) to make upload request. I presume it based on server response.
Therefore,. it would be helpful if there was the way to catch the restart request as the event and based on  the exception / server response.
 
As the work around I had just set restart numbers as zero .and make new request every time based on the server response in onComplete event.

Thanks.

**Comment by gotev** [comment]
@LinkedHK [Here](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/UploadTask.java#L127) is the retry logic. The upload gets retried automatically when an exception gets thrown while performing the upload. Successful upload means that the server responds with an HTTP code between 200 and 299, as you can see [here](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/UploadTask.java#L249). In the upcoming 3.0 release, you will get an [UploadInfo](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/UploadInfo.java) object in every event callback. From this object you can see how many retries have been made, so you can implement your own business logic, being able to cancel the upload when necessary. I think that this feature is enough to accomplish what you described.

**Comment by LinkedHK** [comment]
Thank you for your references.
I've checked the source the retry count doesn't reset(e.g set 0) upon the upload progress (upload resume). is it correct and it's being set 0 only in the run method? Im' sorry if my logic is wrong or I missed something I just believe the retry counter should be set zero when upload has some progress. otherwise it's useless in the long unreliable network. I have had to implement the file uploader for  iOS and faced with similar problem.

**Comment by gotev** [comment]
It's correct that the retry counter is incremented. Follow this example.

1. You setup an HTTP Multipart upload with maximum of 2 upload retries.
2. The upload starts, but then fails at say 50%. Due to how HTTP/Multipart is ([RFC2388](https://tools.ietf.org/html/rfc2388)), the partially uploaded content gets discarded by the server and you have to start over. Be aware that HTTP/Multipart does not support resuming uploads, as it's written in the specifications.
3. The retry counter is incremented
4. A new upload request is made, it starts from the beginning and then fails at 25%. The same applies as what I've written in 2
5. The retry counter is incremented 
6. A new upload request is made, it starts from the beginning and the fails at 65%
7. The retry counter is incremented
8. You have no more available retries, so an exception is fired

What you need is to be able to resume uploads, but then you should use a different protocol, definitely not HTTP/Multipart. If you want, you can extend the library by implemeting one of the resumable upload types (e.g. tus or resumablejs). FTP (which supports resume) is coming in the 3.0 release.

**Comment by LinkedHK** [comment]
@gotev Hi.thank  you for your detailed explanation.  I 've figured out in the code the way retry counter is incremented.but what I didn't know about that HTTP/Multipart does not support resuming uploads. I will not bother with the extending of the library as the project has been already delivered. 
Closing the issue.
