### ISSUE TITLE
List of active tasks

### ISSUE THREAD

**Issue by konalegi** [gotev/android-upload-service#138]
Is there way to get current uploading task list?
Something like:
```java
UploadService.getTaskList()
```

**Comment by hendrawd** [comment]
May i ask why do you need that task list? So maybe we can make a workaround here.

**Comment by hendrawd** [comment]
Currently there are no task list, but instead 
`private static final Map<String, HttpUploadTask> uploadTasksMap = new ConcurrentHashMap<>();` that can't be accessed directly outside of UploadService. If you want to just stop the upload task(s), there are already exist methods to do that.

**Comment by gotev** [comment]
@konalegi that map pointed out by @hendrawd is private by purpose, because it's handled internally by Android Upload Service. If you need a task list (e.g. a list with the uploadID's) what I suggest you to do is implement it in your code. Make a simple array list of strings and add all the uploadIDs into it when you start an upload task.
