### ISSUE TITLE
how to solve that progress and rate are not synchronized in the first second？

### ISSUE THREAD

**Issue by helloyxc** [gotev/android-upload-service#153]
In my case, as the log below, the rate is still 0, when the progress is 10 in the first second:
`07-11 16:17:44.006 2963-2963 FileUploadFragment: The progress of the upload with ID -730961660 is: 0, rate : 0

07-11 16:17:44.346 2963-2963 FileUploadFragment: The progress of the upload with ID -730961660 is: 10, rate : 0

07-11 16:17:45.446 2963-2963 FileUploadFragment: The progress of the upload with ID -730961660 is: 15, rate : 3713

07-11 16:17:46.516 2963-2963 FileUploadFragment: The progress of the upload with ID -730961660 is: 19, rate : 2384`

could you help me solve the issue?

**Comment by gotev** [comment]
The answer to your question is [in the code](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/UploadInfo.java#L139)

**Comment by helloyxc** [comment]
why the waiting time is not same as the broadcast time, just one second?

**Comment by gotev** [comment]
Because those are two completly different things.
Broadcast interval is specified [here](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/UploadService.java#L106). It's not the same because it gets at least one second to get a good upload rate indication, but the default broadcast interval is max 6 notifications per second.

**Comment by helloyxc** [comment]
Could I set the broadcast interval when start a upload?

**Comment by gotev** [comment]
It cannot be set. Are you using placeholders to display upload progress rate?
