### ISSUE TITLE
Why [[UPLOADED_FILES]] Placeholder always shows 0 with HTTP/Multipart uploads?

### ISSUE THREAD

**Issue by hendrawd** [gotev/android-upload-service#180]
Everything working except [[UPLOADED_FILES]]. It will always show 0

`uploadNotificationConfig.setInProgressMessage("Uploaded [[UPLOADED_FILES]] of [[TOTAL_FILES]] at [[UPLOAD_RATE]] - [[PROGRESS]]")`

```
final MultipartUploadRequest multipartUploadRequest = new MultipartUploadRequest(this, url)
.setNotificationConfig(uploadNotificationConfig);//and other parameters
```

**Comment by gotev** [comment]
How many files do you have in your Upload request?

**Comment by hendrawd** [comment]
36

**Comment by hendrawd** [comment]
any number still not working

**Comment by gotev** [comment]
This is a result of a design decision I've made.

`[[UPLOADED_FILES]]` [shows the number of successfully uploaded files](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/UploadTask.java#L537). 
Since the Multipart upload does not support resume, if the connection drops at some point, the operation has to be executed from the beginning, so even if you have uploaded 5 of 11 files, the server will discard them on error and you have to start over. So [as you cen see here](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/MultipartUploadTask.java#L152) the successfully uploaded files are added only when the operation has been completed without errors. 

If you take a look at the FTPUploadTask class, you will see that [each file is added to the successfully uploaded files after it has been completely uploaded](https://github.com/gotev/android-upload-service/blob/master/uploadservice-ftp/src/main/java/net/gotev/uploadservice/ftp/FTPUploadTask.java#L103) because even if the connection drops at that point, the next attempt will be made starting from the next file.

**Comment by hendrawd** [comment]
The connection is not dropped at some point. And i upload multiple files at once with 1 parameter, like this
```
for (String mCurrentPhotoPath : mCurrentPhotoPathList) {
    Uri uriToUpload = Uri.parse(mCurrentPhotoPath);
    multipartUploadRequest.addFileToUpload(uriToUpload.getPath(), "upload[]");
}
```

**Comment by gotev** [comment]
@hendrawd what I've tried to explain is that you can't say that a file is successfully uploaded when you use http multipart, unless all the upload operation is completed, because the server sees all the files you have in your request as a single stream of data

**Comment by hendrawd** [comment]
@gotev oh i see. I will check ftp upload later then. Thanks
