### ISSUE TITLE
Get file name when upload error

### ISSUE THREAD

**Issue by hendrawd** [gotev/android-upload-service#201]
I am curious, how the right way to get the file name from UploadServiceBroadcastReceiver.onError(UploadInfo, Exception). I can set the file name to UploadInfo.uploadId, and then get the file name from that uploadId, but i think that is a hacky thing. Is there any right way to do that?
### Version info
- Android Upload Service version: any
- Android version and API version: any
- HTTP stack (e.g. HurlStack or OkHttpStack): any
### What did you expect?

Method to get file name correctly
## 
## 
### Library initialization code:

``` java
UploadService.NAMESPACE = BuildConfig.APPLICATION_ID;
```
### Request code:

``` java
final MultipartUploadRequest multipartUploadRequest = new MultipartUploadRequest(this, mCurrentPhotoPath, url)
                 .addFileToUpload(uriToUpload.getPath(), "file")
                 .setNotificationConfig(getNotificationConfig(mCurrentPhotoPath))
                 .addParameter("some_parameter", "some_value")
                 .addHeader("some_cookie", "some_cookie_value");
                 .setMaxRetries(0);
multipartUploadRequest.startUpload();
```
#### Where have you added the request code?
- [x] Activity
- [ ] Service
- [ ] Other class (add additional info about it)
### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)

```
// your LogCat output here
```
## 
## 
##

**Comment by gotev** [comment]
Nice question! Actually there is not a way, 'cause you can get only the successfully uploaded file names. I will add this in the next release

**Comment by hendrawd** [comment]
Maybe 1 more field on UploadInfo? Like UploadInfo.fileName?

**Comment by gotev** [comment]
The best will be to have access to the original request directly from the UploadInfo. This means the requests have to be serialized. The problem is that every upload request can define its own additional parameters (e.g. FTPUploadRequest has completely different parameters than HttpUploadRequests like multipart and binary) and the first thing to think of is how to uniform that, so that the serialization and de-serialization could be implemented once for every actual and future upload request protocol.

**Comment by PhilLab** [comment]
PR for retrieving the files left: #277

**Comment by gotev** [comment]
3.3 released and this feature is now available!
