### ISSUE TITLE
Switch from Delegate to BroadcastReceiver

### ISSUE THREAD

**Issue by chamroeunbm** [gotev/android-upload-service#202]
Hi,

I have a Send button in an activity, which will 
- disable while upload in progress
- upload all files to Server (Using parallel upload)
- the button will be invisible when all files are sent
- re-enable if any upload failed.
- delete all uploaded file when receive "OK" response from server(NOT using setAutoDeleteFilesAfterSuccessfulUpload)

**Here comes the problem**
1. if I use Delegate, i can easily detect success, failure, delete success files and update my UI component. BUT if I leave the activity, my activity might get killed and delegate may not be called so i can't delete those uploaded files
2. If I use BroadcastReceiver, I can't update the UI. I saw some people suggest some GET_TASK(ActivityManager), but I think the solution make thing complicated

So what's the best solution?

Thanks;

**Comment by gotev** [comment]
> delegate may not be called so i can't delete those uploaded files

auto delete on successful upload is a feature which exists since 2.0 of Android Upload Service and you can achieve that by simply setting a flag in the request. Check javaDocs linked in wiki. If your server sends you back standard HTTP responses (as it should), the files will be deleted only when the response from server is successful (http code 2xx). If an error occurs, your server should send you different HTTP response codes indicating that an error occurred. In that case you don't need to re-implement the auto delete feature on your own. If you have a fancy server, read further.

> If I use BroadcastReceiver, I can't update the UI. I saw some people suggest some GET_TASK(ActivityManager), but I think the solution make thing complicated

The global broadcast receiver is intended to be used when doing actions which are completely detached from the UI (e.g. your own setAutoDeleteFilesAfterSuccessfulUpload logic if you have non-standard server responses). 

When you call the `startUpload()` method, you will get the associated `uploadId` string and you have to store it somewhere where it's independent of the activity lifecycle (e.g. a singleton in-memory class, a SharedPreference, ...) if you need it to check that particular uploadId status in the future.

Image this scenario:
- The user makes an upload
- You show upload progress in your UI
- The user leaves the activity
- The operation finishes
- The user gets back into the activity

What you have to do is to register a `BroadcastReceiver` in your activity to update the UI when the user is in it. Obviously, when the user leaves the activity, the broadcast receiver will not receive any other event. In the `onResume` you simply have to call `UploadService.getTaskList()` to see which tasks are still in progress. If you have previously saved all the `uploadId`s, you can easily see which of them have been completed since the user left your activity. So you can restore your UI and show additional info for every request.

**Comment by chamroeunbm** [comment]
Thank you very much for spending a lot of time explaining in detail. Much appreciated!

**Comment by gotev** [comment]
You're welcome
