### ISSUE TITLE
getReceiverContext() is not present

### ISSUE THREAD

**Issue by iamdangerous** [gotev/android-upload-service#208]
### Version info
* Android Upload Service version:     3.0.3

* Android version and API version: 
compileSdkVersion 24
    buildToolsVersion "24.0.3"

### What happened instead?
The Android compiler says cannot identify getReceiverContext();

### Steps to reproduce (if applicable):
> public class MediaUploadReceiver extends UploadServiceBroadcastReceiver {
>....
>     @Override
>        public void onCompleted(UploadInfo uploadInfo, ServerResponse serverResponse) {
>        super.onCompleted(uploadInfo, serverResponse);
>        Log.d(TAG,"body asString:"+serverResponse.getBodyAsString());
 >       Context context1 = getReceiverContext();
> .....

##Some of my research
url : https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/content/BroadcastReceiver.java

This class has no protected method

**Comment by hendrawd** [comment]
`getReceiverContext();` method doesn't exist

**Comment by iamdangerous** [comment]
In the above class , in method `onCompleted(UploadInfo uploadInfo, ServerResponse serverResponse)`
I need context to perform db operations like below
>Uri uri = MyProvider.MessageLists.CONTENT_URI;
            ContentValues cv = new ContentValues();
            ...
            context.getContentResolver().update(uri,cv,where,mSelectionArgs);

**Comment by hendrawd** [comment]
I think you can't do that with the current receiver, because some of the fields has private and protected access.

Solution from me, you can copy the current library and import it as a project library and edit UploadServiceBroadcastReceiver.class directly, so you can get the context.

Maybe @gotev can provide a better solution.

**Comment by gotev** [comment]
@iamdangerous you shouldn't perform DB or time consuming operations inside a `BroadcastReceiver`! I suggest you to use the receiver only to start `IntentService`s when you have to do I/O (either to/from disk or the network)

Quoting from @hendrawd response:
> you can copy the current library and import it as a project library and edit UploadServiceBroadcastReceiver.java directly, so you can get the context.

I do not advise to do that, because you loose the purpose of gradle dependency management, and you will not have automatic updates of the library. Best practice suggests that you should never import a project like that. Just keep using the gradle dependency as you do. If you need a custom broadcast receiver and the one provided in the library does not suit your needs, just copy the contents of `UploadServiceBroadcastReceiver.java` inside a new class of you project and make the needed changes. That class only contains the boilerplate code needed to correctly receive the events, so you are safe copying its content or inheriting from that class and introduce your own logic.

**Comment by hendrawd** [comment]
@gotev But, as i said before, some of the fields has private and protected access dependencies to other classes. We can't  just copy the contents of `UploadServiceBroadcastReceiver.java`

And as you mention about long running operation on BroadcastReceiver, yes i agree it is not a best practice, because it can be killed anytime and the process running on foreground too.
More about it can be found at https://developer.android.com/reference/android/content/BroadcastReceiver.html on `Process Lifecycle` section

**Comment by iamdangerous** [comment]
Thanks for helping me out , well I am copying the library locally and will import it into my project .

**Comment by gotev** [comment]
If you're importing the whole library only for the BroadcastReceiver, you are better using the gradle dependency and only copy the Java source of the receiver, this way you'll benefit from easier upgrades for the future releases

**Comment by hendrawd** [comment]
@gotev This is what i mean by we can't just copy paste directly the receiver
![screen shot 2016-11-16 at 7 44 22 pm](https://cloud.githubusercontent.com/assets/9481791/20347645/bf21df26-ac34-11e6-9528-3aa9a4d87833.png)

**Comment by gotev** [comment]
@hendrawd got it. Will be solved in 3.1 when context will get passed to the receiver methods
