### ISSUE TITLE
Upload Bitmap data to server

### ISSUE THREAD

**Issue by MahdiAbdolmaleki** [gotev/android-upload-service#234]
First, thanks for the beautiful work.
How can I upload bitmap image to server?

**Comment by gotev** [comment]
just like any other file on your device. Check [recipes](https://github.com/gotev/android-upload-service/wiki/Recipes)

**Comment by MahdiAbdolmaleki** [comment]
Upload Bitmaps without saving them to the file system.

Bitmap img = null;
ByteArrayOutputStream stream = new ByteArrayOutputStream();
img.compress(Bitmap.CompressFormat.PNG, 100, stream);
byte[] imageData= stream.toByteArray();

How to upload imageData to server?

**Comment by gotev** [comment]
The library does not support uploading a byte array directly because of the following things:
* passing large data in the intents used to start the service is not advisable, as per android docs
* if the upload fails after the retries or your app gets killed by the system, you can't automatically retry it when the service or your app gets restarted, because that byte array will be lost since it's in-memory only.

So if you pass large dateset across your app in general, avoid that, as it's system and memory inefficient. What I advise you to to is to persist your byte array in a temporary file inside your appìs cache, get the file path, pass it to the upload service and set `setAutoDeleteFilesAfterSuccessfulUpload(true)` on the upload request, so as soon as the upload gets completed successfully, your temp file will be automatically deleted.

**Comment by MahdiAbdolmaleki** [comment]
Thank Alex Gotev.
