### ISSUE TITLE
Multipart Upload not completing on poor and dodgy networks

### ISSUE THREAD

**Issue by mmintz** [gotev/android-upload-service#235]
Multipart upload .

### Version info
* Android Upload Service version: 3.1
* Android version and API version:  4.4 , 5.0 , 5.1 , 6.0, 7,0, 7,1
* HTTP stack (e.g. HurlStack or OkHttpStack): OkHttpStack

### What did you expect?
Upload files on slow connection
### What happened instead?
Goes untill 99% and then retries. Never uploads in the end
### Steps to reproduce (if applicable):
Just try to upload any file using 1Mb/s upload connection

### Additional info
No need for me to provide server code or anything. Just try uploading on any Android version above kit kat on a DODGY , SLOW connection. This issue has been reported before but no change. Before the upload progress was not resetting (when the upload was retried) so you would get uploads with progress 300%. Now progress is fixed but files still not get uploaded.

**Comment by gotev** [comment]
@mmintz multipart uploads and binary uploads are not the best when you have a slow or dodgy connection, that's known, because if the connection drops, you have to start over. It's just how the protocol works. By dynamically tuning network timeouts to greater values (which you can do in Upload Service) you can increase the fault tolerance. Beyond that, there's really nothing more we can do client side. The best is to support resumable uploads (check #171 ).

> No need for me to provide server code or anything

Any advice on how to simulate an environment like yours? Have you tried to measure the bandwidth between you and your server, the percentage of lost packets and latencies?

> This issue has been reported before but no change. Before the upload progress was not resetting (when the upload was retried) so you would get uploads with progress 300%. Now progress is fixed but files still not get uploaded.

Are you referring to #161 ?

**Comment by mmintz** [comment]
Thank you so much for the great response. You have done great work man. I will try to give some info on how to simulate the exact same environment asap.
Yes i was refering to #161 . The difference is that yes now its fixed it does not go beyond 100 % but what i realized is that even with huge timeouts most files are going untill 99% and never finish (fail). Then it retries depending on the ammount of retries i set on the muplipart request but NEVER uploads the files. Goes untill 99% and then fails after some period of time.

Thanks again for the response!
Great work !
