### ISSUE TITLE
Add onRetry callback

### ISSUE THREAD

**Issue by lolet** [gotev/android-upload-service#236]
Consider following case:
- I start to upload a large file or have slow connection with token authorization which has an hour expire time
- When an hour passed away the connection has been lost and the upload has been restarted
- Unfortunately the token is stale and its invalid now. Upload fails.

Unfortunately the `onError` callback is called when upload fails at all. But if there would be a callback method `onRetry` I could react on thrown error and refresh token. I already implemented that, but there's a problem: I use `HttpUploadRequest.addHeaders` method to set the auth token and I wonder what would be the best way to update the `UploadTask` request headers.

**Comment by gotev** [comment]
I recommend you to use OkHttp stack with a request interceptor to set authentication tokens. Check also the OkHttp Authenticator. Headers set with interceptors are added to the Upload Service requests starting from release 3.1. update if you use an old version.

**Comment by gotev** [comment]
Doing some thinking about how to add an `onRetry` callback. The discussion is open.

First of all, it means making the initial request accessible and modifiable and that will require a major refactoring in the library.

Ideally, you want to have something like:
```java
public boolean onRetry(Context context, int attempt, UploadInfo info, 
                       UploadRequest originalRequest, Exception exception) {
    // your code
    // if the retry has to be done, return true, otherwise false
    return true;
}
```
As of today, this callback will be called inside the `UploadServiceBroadcastReceiver` or the `UploadStatusDelegate`, which are both run on the main thread. 

@lolet I imagine that to refresh your token, you need to perform a network request from within the `onRetry` callback and set the new one after you got the response. This means performing a blocking call or something that requires I/O or takes some time. To be able to do that, the only solution I can see is that the `onRetry` gets called in the background, in the same thread where the `UploadTask` is running, to prevent `NetworkOnMainThread` and blocking the UI. This is easier to do if you set a delegate, but problematic when you use `BroadcastReceiver` which receives the `Intent` on the main thread and has no way of performing something time-consuming.

**Comment by lolet** [comment]
Please look at my commit, it's kinda hacky but it works for my needs. Unfortunately it doesn't work completely for `BroadcastReceiver` because of lack of access to `HttpUploadTask` instance. Also I had to throw exception In `HttpUploadTask` because onError / onRetry wouldn't been called if server returned with non 200.

**Comment by gotev** [comment]
@lolet I've seen the commit. 

First, a little explanation. The `onError` gets called only if you can't reach the server because it's down or you have network issues. That's how I've decided to implement it initially in the library. Maybe it will be more appropriate to call `onCompleted` only if the server responds with `200 <= httpCode < 300` and call `onError` for both network connectivity exceptions and server errors, by also providing the server response.

Next, I would call `broadcastRetry ` only if `shouldContinue = true`, otherwise it will be called even if the request gets cancelled in some cases.

Another thing which has to be done is request serialization, to be able to access the original request and fully modify it (headers, parameters and files) in the `onRetry` method.

After doing all the above mentioned refactorings and implementations, the main problem still persists: how to do time-consuming things inside the `onRetry` method, which gets called on the main thread.

**Comment by gotev** [comment]
The above ideas are subject to the same considerations I wrote [here](https://github.com/gotev/android-upload-service/issues/260#issuecomment-318662746). Unless a solution is found, this feature will be impossible to implement for broadcast receivers. If in a month from now nothing comes up, I will close this marking it as `wontfix`.

If you need `onRetry` callbacks to renew tokens or for authentication matters, consider using OkHttp stack with UploadService, together with Authenticator and Interceptors, which solves the problem.
