### ISSUE TITLE
org.apache.commons.net.ftp.FTPConnectionClosedException: Connection closed without indication.

### ISSUE THREAD

**Issue by moter** [gotev/android-upload-service#274]
org.apache.commons.net.ftp.FTPConnectionClosedException: Connection closed without indication.

**Comment by gotev** [comment]
Please follow the isdue template and provide more details. issues like this do not provide any way of replicating the problem and spotring if it's an Apache Commons FTP bug or an Android Upload Service bug. Thank you!

**Comment by moter** [comment]
English is poor, please forgive me。

Using FTP to upload files to the window server was correct yesterday, but it went wrong today. The device system is android4.4.4

**Comment by gotev** [comment]
Sorry, but you have to follow what is in the issue template and provide necessary details, otherwise I couldn't help you in any way

**Comment by moter** [comment]
The same file, second pass will make mistakes ,and return "Error while uploading: xx to xx"
I don't understand the code 

 try {
            String remoteFileName = getRemoteFileName(file);
            if (!ftpClient.storeFile(remoteFileName, localStream)) {
                throw new IOException("Error while uploading: " + file.getName(service)
                                      + " to: " + file.getProperty(PARAM_REMOTE_PATH));
            }
            setPermission(remoteFileName, file.getProperty(PARAM_PERMISSIONS));
        } finally {
            localStream.close();
        }

**Comment by gotev** [comment]
The exception is thrown because the transfer of the file to your FTP
directory is not possible. I don't have the Apache Commons Net FTP docs at
hand, but this may be due to permission policy for your FTP user or if the
file already exists, in which case it doesn't get overwritten.

Can you successfully upload the file for the first time? If I understand
correctly, you get the exception only the second time you try to upload it.

Il 14 giu 2017 3:59 PM, "叉叉裤" <notifications@github.com> ha scritto:

The same file, second pass will make mistakes ,and return "Error while
uploading: xx to xx"
I don't understand the code

try {
String remoteFileName = getRemoteFileName(file);
if (!ftpClient.storeFile(remoteFileName, localStream)) {
throw new IOException("Error while uploading: " + file.getName(service)
+ " to: " + file.getProperty(PARAM_REMOTE_PATH));
}
setPermission(remoteFileName, file.getProperty(PARAM_PERMISSIONS));
} finally {
localStream.close();
}

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/gotev/android-upload-service/issues/274#issuecomment-308439949>,
or mute the thread

**Comment by moter** [comment]
Successfully upload the file for the first time.But,Some FTP servers can upload second times。
I'll see if the FTP service is insufficient。
Example：
  new FTPUploadRequest(mContext, _ip, _port)
                            .setUsernameAndPassword(_accout, _pwd)
                            .addFileToUpload(path, to)
                            .setNotificationConfig(config)
                            .setCreatedDirectoriesPermissions(new UnixPermissions("777"))
                            .setSocketTimeout(30*1000)
                            .setConnectTimeout(30*1000)

**Comment by gotev** [comment]
Here it's [storeFile] method (https://commons.apache.org/proper/commons-net/apidocs/org/apache/commons/net/ftp/FTPClient.html#storeFile(java.lang.String,%20java.io.InputStream)) JavaDoc. The method should overwrite the existing file the second time you try to make an upload. 

The best way to check if the problem is in the library or in your FTP server config is to use one of the [test FTP servers](https://github.com/gotev/android-upload-service/blob/master/uploadservice-ftp/README.md)

**Comment by moter** [comment]
You are right，this is FTP server Permission denied。
thanks
