### ISSUE TITLE
Notifications constantly switch positions

### ISSUE THREAD

**Issue by lxs137** [gotev/android-upload-service#307]
Hi, if I create some "BinaryUploadRequest" to upload some files at the same time. I find that the upload notifications constantly switch positions in Notification bar, it is very strange. How can l fix it. Thank you!
My UploadNotificationConfig is:     

        UploadNotificationConfig config = new UploadNotificationConfig();
        PendingIntent clickIntent = PendingIntent.getActivity(context, 1,
                new Intent(context, AttachmentListActivity.class), PendingIntent.FLAG_UPDATE_CURRENT);
        config.setTitleForAllStatuses("Upload—" + filename)
                .setRingToneEnabled(true)
                .setClickIntentForAllStatuses(clickIntent)
                .setClearOnActionForAllStatuses(true);

**Comment by gotev** [comment]
When the upload service starts with foreground execution privileges, it needs to display an ongoing notification in the Notification Center, as per Android design. The upload service [is a task runner](https://github.com/gotev/android-upload-service/wiki/Developer's-manual), so it does not have its own notification. For this reason, one of the running tasks has to take care of holding and updating the foreground notification. This has been implemented starting [from this commit](https://github.com/gotev/android-upload-service/pull/69/commits/fab125b4732f1e8a8e45a475e20b8effad3a15b0) when multiple parallel uploads were introduced.

The principle is the following: 
* imagine N tasks running in parallel
* each task sends a broadcast whenever there is some progress to show
* you do not know in advance which task will finish first
* whenever a task sends a broadcast update, the most recent one [holds the foreground notification](https://github.com/gotev/android-upload-service/wiki/Developer's-manual) and updates it

This approach works without problems to solve the problem of keeping the foreground notification always updated, but the downside is that you will experience the ping-pong of notifications you described, because the most recent notification will always be the first one. I'm open to new ideas to improve this. Feel free to fork, experiment and send a pull request.

**Comment by lxs137** [comment]
Thank you! It fix my problem.
