### ISSUE TITLE
why upgrade min sdk to 18

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [gotev/android-upload-service#425]
hi 
why did you upgrade min sdk to 18?
my project min sdk is 16.
thanks

**Comment by gotev** [comment]
This is because starting from 3.5.0 the library supports API 28 (Previous ones until API 26) and it supports the last 10 API versions, therefore minSdk is now API 18. Moreover, devices running versions older than Android 4.3 (API 18) are now a small fraction: https://developer.android.com/about/dashboards/
