### ISSUE TITLE
Question: Is this configurable to support s3 uploads?

### ISSUE THREAD

**Issue by carotkut94** [gotev/android-upload-service#451]
Is there any way it can be configured to upload the files to s3 bucket

**Comment by gotev** [comment]
Hi! S3 uses a proprietary multipart protocol. Since it has an initial call and then N calls for each part to be uploaded, current upload service implementation is not easy to use for that purpose. That being said, it's possible to make S3 specific implementation in a dedicated plugin (like upload service FTP for example)
