### ISSUE TITLE
how can I get uploading file status in my fragment with 4.2.0 version (Monitoring uploading status)

### ISSUE THREAD

**Issue by kunjanrshah** [gotev/android-upload-service#490]
Hi Gotev, 

I have added below dependency in my gradle file.
implementation 'net.gotev:uploadservice:4.2.0'

I have written below method in onCreateView Method. Now I wanted to display Success Dialog while uploading status completed. so how can I do this ?

val request= MultipartUploadRequest(activity!!, serverUrl = UPLOAD_DOCUMENT)
                            .setMethod("POST")
                            .addFileToUpload(
                                    filePath = filePath,
                                    parameterName = getString(R.string.uploaded_file)
                            )
                            .addParameter(getString(R.string.filename), uploadedFileName)
                            .addHeader(getString(R.string.apikey), AppConstants.API_KEY_VALUE)
                            .startUpload()

**Comment by ashishkharcheiu** [comment]
Also, please make a wiki on migrating from 3.5.2 to 4+
From UploadStatusDelegate to its alternative on 4+ version wiki as well.

**Comment by gotev** [comment]
Added a wiki page with some starter examples: https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads

You can cover many more scenarios using the `RequestObserver`, but the wiki is not meant to cover them all, because different apps have different use cases and specific needs. You are however welcome to enrich the documentation with additional examples 🎉
