### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by behlsoft** [gotev/android-upload-service#525]
Hi 
I just wanted to confirm few things before using this great library.
If i started this service to upload my files and there is no internet, will it automatically start whenever i will have internet?
If i started this service to upload my files and there is no internet and i terminate my app or remove it from stack, will it automatically start whenever i will have internet without opening my app?

Thanks in advance
Rohit Behl

**Comment by gotev** [comment]
Hi!

The library has a backoff retry policy, so if you start an upload, you can set a time interval and max number of retries before it fails.

If you kill your app, since the upload happens in a service launched by your app, the upload gets killed, too.

Network connectivity detection is not bundled in on purpose, to remain as generic and lightweight as possible and allow a vast variety of different implementations, which has to be done by you to meet your specific needs.

**Comment by behlsoft** [comment]
Thanks for the quick reply. Cheers!
