### ISSUE TITLE
Guidance on implementing S3 Upload Service

### ISSUE THREAD

**Issue by barchard** [gotev/android-upload-service#527]
**What do you want to achieve?**
Do you have any guidance on implementing a direct S3 service using AWS' S3 transfer service SDK? We are trying to implement S3 as a service here without directly using HTTP headers + signing + auth

**What have you tried to do?**
Reviewed Code and Wiki

**Which Upload Service Version are you using?**
4.3.0

**On which Android version?**
Android 9/10

**Additional info**
Trying to wrap the AWS SDK for use with `android-upload-service`

**Comment by gotev** [comment]
Hi @barchard ! The core principles are:
- implement an upload request. It's a builder which creates an intent that starts the service.
- implement an upload task. It's the receiver of the intent you created with the upload request. It gets executed in the background inside the service.

You can use existing multipart, binary and ftp implementations as examples and write your own plugin which wraps the S3 SDK. FTP module may be the best starting point, because it shows you how to implement a complete request builder and task handler together with an external library.

**Comment by chiragpatel92** [comment]
Hey. I want to achieve the same functionality. Did you get the solution?

**Comment by gotev** [comment]
@barchard will be glad to see your plugin when it's ready! Closing this issue as there's nothing more I can do here.
