### ISSUE TITLE
Set dynamic notification title based on uploading file name 

### ISSUE THREAD

**Issue by EngKhAboshama** [gotev/android-upload-service#532]
Please can you give me an example about how I can customize the notification title based on file name?

**Comment by gotev** [comment]
Just add `.setNotificationConfig()` passing an [UploadNotificationConfig](https://github.com/gotev/android-upload-service/wiki/Configuration#uploadnotificationconfig) to your request, before calling `.start` or `.subscribe`. You have full control of both `title` and `message`.

**Comment by EngKhAboshama** [comment]
I'm using ExampleSingleNotificationHandler class which extends AbstractSingleNotificationHandler class, so how can I resolve it?

**Comment by EngKhAboshama** [comment]
Also, I'm using the following code
MultipartUploadRequest(context, api_url).
        .addFileToUpload(queryParams[0], parameterName = "attachment", fileName = queryParams[1]).setNotificationConfig(notificationConfigFactory).

I want to use the fileName during updating the notification title in the background service. 

My Second point, I want to prevent notification from displaying each a few seconds from top of screen . I want to display it just one time and update the notification manually without displaying it each time on top of screen

**Comment by gotev** [comment]
Ok, so now you told me some details which you didn't mention before.

You're using a custom notification handler, based on the provided example of a single notification handler. Be sure to have registered it in your App initialization like explained [here](https://github.com/gotev/android-upload-service/wiki/Configuration#notification-handler).

Since you're using a custom notification handler, it's up to you to choose which configs set like that to honor: `.setNotificationConfig(notificationConfigFactory)`

In `updateNotification` method you can access each task's config in this way:

```kotlin
tasks.entries.forEach { (uploadID, taskData) ->
    val notificationConfig = taskData.config
}
```

the example provided does not honor notification configs by default on purpose, as it's just a proof of concept. There are many different strategies applicable to honor configs, but favoring a particular one for the example would have disallowed others.

From what you described so far, you may not need to honor per-upload notification configs it at all (by concentrating all the notification display logic in the custom notification handler and removing the `setNotificationConfig` from the request code) if you need the same exact behavior for all the uploads in your app.

However, if you're interested, you can look at [NotificationHandler](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/observer/task/NotificationHandler.kt) implementation to see how to honor a per-notification setting. 

> I want to use the fileName during updating the notification title in the background service.

In the `updateNotification` method, you can get the name of the files being uploaded by looping the `tasks` map (add `private val` to the `service` parameter in your class constructor to be able to access it). 

```kotlin
tasks.entries.forEach { (uploadID, taskData) ->
    val fileNames = taskData.info.files.map { file -> 
        file.handler.name(service)
    }
}
```

> I want to prevent notification from displaying each a few seconds from top of screen

In the `updateNotification` method, return null if you don't want to update the notification or return the builder if you want to update the notification.

> I want to display it just one time and update the notification manually without displaying it each time on top of screen

What do you mean with `display it just one time` and `update the notification manually`?

**Comment by EngKhAboshama** [comment]
Thanks for your reply. 

About this point => What do you mean with display it just one time and update the notification manually?
I want to update the old notification object without create new one, so please do you create notification each time or just updated the created one?

**Comment by gotev** [comment]
@EngKhAboshama Android Upload Service promotes immutability. Every time `updateNotification` gets called, you receive a fresh builder.
