### ISSUE TITLE
MultiPartUploadRequest is not serializable.

### ISSUE THREAD

**Issue by cannizarro** [gotev/android-upload-service#536]
Is there any alternative way to pass a serializable object in an intent containing a MultiPartUploadRequest as a data member?

**Comment by gotev** [comment]
It's not clear what are you trying to achieve why are you needing the request to be serializable.

**Comment by cannizarro** [comment]
I need to save the UploadRequest so that I can reuse it later for retries or sending the upload whenever the user desires. The object that I use implements Serializable and when I try to send this object using Intent, since MultipartUploadRequest is not serializable, it throws an error.

**Comment by gotev** [comment]
Request builders are not meant to be persisted as they serve the sole purpose of creating the intents which starts the Upload Service.

What all the builders have in common is that they create the [UploadTaskParameters](https://github.com/gotev/android-upload-service/blob/master/uploadservice/src/main/java/net/gotev/uploadservice/data/UploadTaskParameters.kt) data class which is then passed to the service, along with the class name of the task to be started.

To achieve the desired outcome, we should think about how to properly serialize/deserialize the upload task parameters together with the class name. I'm open to proposals and contributions 😉

**Comment by cannizarro** [comment]
Thanks for your insight, it was greatly helpful. The outcome that I am going for can be achieved by the UploadTaskParameters.

**Comment by gotev** [comment]
@cannizarro bear in mind it's a parcelable. Which strategy do you intend to use to serialize/deserialize?

**Comment by cannizarro** [comment]
I was using header as well as some parameters in the upload request and I was quite not clear of the `additionalParameters` member of the `UploadTaskParameters` data class. So I made my custom data class for the required info for building another UploadRequest. Thanks for your concern, you have really built an awesome library.

**Comment by gotev** [comment]
@cannizarro thank you for the appreciation of my work and those of the other contributors so far ❤️ 

`UploadTaskParameters` is meant to be extendable. `additionalParameters` contains different things if you make a binary, multipart or http upload and is there to support protocol-specific parameters and allow also third party upload task plugins and implementations of custom builders.

Actually `UploadTaskParameters` contains also the notification config (which can contain also pending intents) and now this is the limiting factor to be able to serialize/deserialize the requests, which can not only solve your use case, but also allow new native integrations, like WorkManager, to allow people using the library to do both immediate and also deferred uploads. 

You can certainly make your own data classes which holds the parameters you need and then create requests from them, but I was thinking about how to extend the library to allow use cases like yours out of the box, because they have now become more common than before. If you have some ideas, I'll be curious to discuss them 😃

**Comment by gotev** [comment]
@cannizarro what do you think about this? #538 feel free to comment on the PR

**Comment by cannizarro** [comment]
Should've asked you earlier, when I first had this problem. You're the best, man 💚! See, I'm still a student and my exams are going on and I'm in a middle of an internship, but I'll love to contribute when I get free. Thank you.

**Comment by gotev** [comment]
@cannizarro always challenge yourself and try to solve problems autonomously, even if they seem too big. It's good you haven't asked early on. Going past your limits is the single most valuable thing you can do to get better. Programming is a neverendless job and as long as you are passionate about it, it's extremely rewarding in many different ways. Wish you the best!

Meanwhile, you can test & experiment with the new `4.5.0` and the new persistent upload feature: https://github.com/gotev/android-upload-service/wiki/4.x-Usage#persistence
