### ISSUE TITLE
Implement FTP Upload resumability

### ISSUE THREAD

**Issue by Borna-f** [gotev/android-upload-service#547]
**Describe the bug**
FTP upload does not continue from where it is left on failure. Probably the function "calculateUploadedAndTotalBytes" needs to be revisited.

**To Reproduce**
1. input credentials from Test FTP server: https://dlptest.com/ftp-test/
2. Run demo app
3. Choose a file to upload on FTP
3. Disconnect wifi during the upload process
4. Reconnect wifi
5. Observer that the upload starts from beginning rather than resume from where it was left

**Expected behavior**
The upload should resume from where it was left.

**OS and Lib versions (please complete the following information):**
- Android Upload Service version:  4.5.1
- Android 10
- FTP Upload

**Comment by gotev** [comment]
I confirm this is a feature which is not implemented yet in the FTP module.

You're welcome to share your ideas about how to achieve this and to make a PR 😉

**Comment by Borna-f** [comment]
Does this need a test that replicates the scenario? 😃 I though you want to fix it as you know the code better. lol
But I based my other modules implementations on FTP implementation. I am not using FTP but if you happen to find some time to apply a fix, it would be nice as I can replicate the fix to my box/other upload implementations.

Thanks

**Comment by gotev** [comment]
Yes, FTP Module has zero tests on it, so before doing anything some tests should definitely be made.

It's a module which I don't use personally since 2013. The "expertise" on that is long gone 😄

However, resuming FTP uploads is not a fix, but a new feature, which requires handling resumability in general and to study Apache Commons FTP lib separately to achieve that. I simply don't have the need at the moment, but it's OSS and everyone could improve it and make it if needed.

Unless some specific resumability support is required in the upload service core, I don't think you can reuse anything as it will be Apache Commons FTP stuff.

**Comment by gotev** [comment]
Closing this as it's a while without any activity. Everyone willing to contribute such a feature is welcome with a PR!
