### ISSUE TITLE
Using library with Coroutines or WorkManager

### ISSUE THREAD

**Issue by 3liRashad** [gotev/android-upload-service#569]
**What do you want to achieve?**
I am trying to make a request inside a workmanager without a service

**What have you tried to do?**
I fetched the code and found that startUpload() function using startService(intent) so I came here to ask.

**Which Upload Service Version are you using?**
Latest

**On which Android version?**
Android 10/11

**Additional info**
Any information which you want to add to better explain your issue.

**Comment by gotev** [comment]
Hi! At the current state of the art WorkManager/Coroutines are not supported at all, but it's the next step of the evolution planned for the library. I'm open to proposals and PRs!

**Comment by gotev** [comment]
@3liRashad starting from the current state of the art, what you will ideally want to write to start an upload? Also, do you expect notification handling to work the same as now?

**Comment by 3liRashad** [comment]
@gotev Sorry for late reply.
I was thinking about making the upload function as Suspend Function so anyone can call it from his Coroutine scope.
Also I expect notification working as same as now.

**Comment by gotev** [comment]
@3liRashad porting to Coroutines is a necessary step going forward and the next one I want to do. You are more than welcome to contribute 😎

Currently the architecture can be synthesized down to this:
- you have a request builder (e.g. Multipart, Binary) which builds an Intent
- when startUpload is invoked the intent gets fired
- the service receives the intent, creates the task and adds it to a queue
- a thread pool consumes the queue and invokes task methods, including notification handler

Currently you can also configure the number of concurrent threads.

I think the best point to start with is to make the tasks use Coroutines instead of blocking threads and get rid of the ThreadPool entirely, but without losing the possibility to configure the number of parallel uploads.

This first level of refactoring will leave the public API completely unchanged, but will be a major step forward.

Regarding WorkManager, I started studying it and without previous experience on it, so my current vision is certainly not complete. I've seen that its core architecture is still based on blocking threads and that Coroutine powered tasks available just do runBlocking at a certain point, which defeats many of the advantages. Things could hopefully change, but at the time of this writing, this is the state of the art I observed.

Also, given a look at WorkManager AFAIK we have two choices going forward:
- use WorkManager inside the library and hide it completely from library users. This would defeat many WorkManager advantages such as task scheduling and task concatenation, unless we do another level of wrapping
- make upload service a WorkManager task provider which gives you Multipart, Binary and FTP out of the box. This would completely destroy current public APIs and will make users think by the rules and programming style promoted by WorkManager. Also, I'm not sure how can one still leverage notification handling without a lot of boilerplate code at that point.

Those are my thoughts and how I see things at present day. There are choices to be made and further paths and ideas to be explored. Everyone is welcome to be part of it 🤩
