### ISSUE TITLE
setMaxRetries is not work

### ISSUE THREAD

**Issue by savenko** [gotev/android-upload-service#575]
```
MultipartUploadRequest(context, serverUrl = URL+"upload-image")
                            .setMethod("POST")
                            .addFileToUpload(
                                filePath = ImagePath,
                                parameterName = "Image"
                            )
                            .setMaxRetries(50)
                            .startUpload()
```

On server side i set Exception. I expect what Upload service will try to do 50 tries. But that not happened. Why?

**Comment by gotev** [comment]
Retry mechanism triggers when there's a communication failure to/from the server due to connectivity problems (e.g. timeout, broken pipe, server unreachable, no network connection on the device)

If your server sends a 4xx or 5xx response, the retry mechanism will not be triggered, as the communication happened correctly, but something on your server was broken and you will receive the error response in onError.
