### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by SudoDios** [gotev/android-upload-service#596]
UploadTask - (uploadId: c44c3509-c493-4230-a100-1f9a7be76323) - error

**Comment by SudoDios** [comment]
Connects to ftp but does not upload

**Comment by SudoDios** [comment]
how to upload to subdomain

**Comment by gotev** [comment]
@SudoDios I have to remember you that this is an issue tracker.

Things almost never work out of the box for a vast variety of reasons. The code is open, we're programmers. Something not working in your specific use case does not mean automatically it's a library bug or that you should ask a library maintainer of a general purpose solution to solve your specific use case asking random questions.

I am more than happy to help when I see issues with all the relevant details (following issue templates), replicable bug evidence, steps to reproduce and new ideas to enhance the library.

Unfortunately this issue seems more or a personal log of events and therefore there's nothing to do here.
