### ISSUE TITLE
Get Request Status By Upload ID 

### ISSUE THREAD

**Issue by Tahaelhosseny** [gotev/android-upload-service#600]
First, I want to advance a big thanks to you for your previous response, second, I want to ask you if there is any way to get request status by upload id?

**Comment by gotev** [comment]
It looks like you haven't checked the wiki before asking this question

**Comment by gotev** [comment]
Take a look here: https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads 😉

**Comment by Tahaelhosseny** [comment]
I have read it, but let me tell you what I want to do.
I want to loop for all upload task lists when reopening the application so that update my cached list with the last status and display the list for users.

like that : 

for (upload in uploads )
{
//check the status by upload.uploadId
//display the stats in task fragment android
}

**Comment by gotev** [comment]
You can get [the list of currently active upload IDs](https://github.com/gotev/android-upload-service/wiki/4.x-Usage#management-apis-programmatically-get-running-uploads-and-stop-them-) and use a [RequestObserver for specific upload IDs](https://github.com/gotev/android-upload-service/wiki/Monitor-Uploads#subscribing-to-specific-upload-requests)

**Comment by Tahaelhosseny** [comment]
if the upload is finished before I RequestObserver for a specific upload, the observer will return the result or no?

**Comment by Tahaelhosseny** [comment]
Another strategy may be to use a GlobalRequestObserver for all uploads and cache yourself all the latest upload info data you receive. 
in this scenario what I have to do if app is closed

**Comment by gotev** [comment]
> if the upload is finished before I RequestObserver for a specific upload, the observer will return the result or no?

Using list of currently active upload IDs + RequestObserver means that if an upload is completed (either with success or error) while your app is in the background, when you get the task list again after you get back in foreground, that ID will no longer be in the list.  

> in this scenario what I have to do if app is closed

What do you mean by `app is closed`? 
- `app is killed by the user`: all the uploads are going to be interrupted (because you kill the root process of the app) and you have to recreate them and start them again.
- `app is put in the background but not killed`: using GlobalRequestObserver for all the events you should (unless some vendors does fancy stuff with android lifecycles) still receive the events and be able to have also the last event fired also for completed uploads (either with success or failure).

**Comment by Tahaelhosseny** [comment]
Big thanks for your response almost all my problems and needs solved till now.
thank you

**Comment by gotev** [comment]
Awesome 😎
