### ISSUE TITLE
Notifications cannot be disabled

### ISSUE THREAD

**Issue by 39otrebla** [gotev/android-upload-service#621]
**Is your feature request related to a problem? Please describe.**
In our Application we have both (potentially) long-running uploads and very quick ones (<1 MB). For the latter case, we don't want a Notification to appear.

Also, there are use cases where it is important that the upload continues if the app is sent to background (so it makes sense to use this library), but the upload itself is a non-core feature (or even something the user didn't start voluntarily), so it doesn't make sense to show a notification.

**Describe the solution you'd like**
I'd like to have a setter to enable/disable notifications on a Request instance (not globally).

**Describe alternatives you've considered**
An alternative would be to create a Notification Channel with the lowest priority, and then use it via `UploadNotificationConfig`. But in this way:
- it would still be visible in Application Settings
- it would still require a lot of configuration (`progress` StatusConfig, `error` StatusConfig, etc, etc) for something that no one in team would even want to show

**Are you willing to implement it and maintain it?**
- [ ] Yes
- [X] Can implement it with a Pull Request, but not maintain it
- [ ] No

**Comment by gotev** [comment]
Google requires the notification to appear within 5 seconds after service is started, so the notification is always needed, otherwise you will have a crash.

They have posed increasing limitations and constraints on Services, to promote using WorkManager instead.

When the library was born and up to Android 8 your use case was fully supported, but afterwards, as a result of increasing limitations.amd constraints, the library had become best suited for user initiated uploads which may require some time and for which you want to show a progress.

**Comment by 39otrebla** [comment]
Are you implicitly saying that addressing #610 would unblock this feature?
