### ISSUE TITLE
Java Code Samples?

### ISSUE THREAD

**Issue by derwaldgeist** [gotev/android-upload-service#643]
Hi, this library looks very interesting, especially since it seems to be actively maintained. I need background uploads for an Android app that is built with Unity, so I'd like to develop a Unity plugin for this. I am familiar with Unity plugin development, yet I am not a very seasoned Java developer nor do I know Kotlin at all. Hence, I would highly appreciate any Java source code samples. Are these available somewhere? The repo says the library would be fully interoperable with Java, but the samples are all in Kotlin.

Another quesion that came up: My app needs to get notified once an upload is finished, even if the app is running in the background, to do some follow-up tasks (including network activity). Would this possible with this service, i.e. is it possible to "wake-up" the main app?

**Comment by gotev** [comment]
Hi and thank you for your interest in the library! 

If you know C#, Java has similar syntax and paradigm. Library and example apps are all in kotlin since 2019 and I don't have any Java example.

You can check the wiki for the lifecycle and events fired by the library. It should be exhaustive, but if something's missing, feel free  to ask!
