### ISSUE TITLE
How to use it on eclipse?

### ISSUE THREAD

**Issue by ProgramAPE** [gotev/android-upload-service#79]
I want to use the upload-service on eclipse. But the project just provide the .aar file. So how can i use it on eclipse?

**Comment by alexbbb** [comment]
Hi, I think there's a way for gradle to generate also the `.jar` when creating the release version of the library, but I haven't had time to investigate how to do it after that I've migrated the project to Android Studio. If you have some suggestions, we can try them. 
This might be useful: 
* http://stackoverflow.com/questions/23777423/aar-in-eclipse-ant-project
* http://stackoverflow.com/questions/27309203/does-adteclipse-supports-apklib-or-aar-now-upto-adt-v23-04

**Comment by ProgramAPE** [comment]
Thank you so much! I will have a try.

**Comment by ProgramAPE** [comment]
I followed StackOverflow try this:
--------- tried for sevearl weeks, i turned to idea with gradle. as far as i kown, apklib is supported, while aar is not full supported. Here is one way to use AAR.
just unpackage the aar into a folder, then import into eclipse as a library project. do not forget to add the classes.jar into build path. then add a library project dependency to you own project.------
then:
I create a testing project with two classes:
1. application:
public class AppInitializer extends Application{

	@Override
	public void onCreate() {
		// TODO Auto-generated method stub
		super.onCreate();
		UploadService.NAMESPACE = "com.dmicheal.door";
	}
	
}

2. An Activity and add the upload event on a Button onClick event function:
            final String uploadID = UUID.randomUUID().toString();
	    final String serverUrlString = "http://192.168.10.45:3000/upload/multipart";

	    try {
	        new MultipartUploadRequest(context, uploadID, serverUrlString)
	            .addFileToUpload(file_path+"/doorknocker_log.txt", "test")
	            .setNotificationConfig(new UploadNotificationConfig())
	            .setMaxRetries(2)
	            .startUpload();
	        Log.d("upload", file_path+"/doorknocker_log.txt");
	    } catch (Exception exc) {
	        Log.e("AndroidUploadService", exc.getMessage(), exc);
	    }

Everything goes well. But when the app start, click the Button, Nothing happens. I don't know why. The same result when I port the all source code to my project.  
Did I miss something?

**Comment by alexbbb** [comment]
When you import the project with maven or gradle, there's a step called "manifest merger" which is performed automatically. In your case you have to do that manually. If the service does not start, I think is due to this fact. Check this older revision of [README.md](https://github.com/alexbbb/android-upload-service/blob/ae5ba83b0be89e47a3b40196dc00dbe6b24304c8/README.md) which describes how to register the service in your manifest. Be sure to also copy and paste all the required permissions from the library manifest to yours and to add dependencies for Android support v4 and Android support v7. The versions used are listed in library's build.gradle in uploadservice folder. After that the service should work. The drawback is that when I'll release a new version, you will have to manually do all this stuff to upgrade. I'll check how to generate also library jar for the next release.

**Comment by ProgramAPE** [comment]
So nice of you. Thank you so much.

**Comment by gotev** [comment]
After some research, I discovered that JAR packagng is not possible because `com.android.support:support-v4` library needs AAR packaging, since it adds some resources. That library is needed for the notifications, so if you want to use the library in eclipse you can either find a way to use AAR dependencies or checkout the project sources and link them into your app.
